#!/bin/bash

CMD=$*
SERVERPID=""
SERVERACTIVE=false
# http://stackoverflow.com/questions/14964402/spawn-server-and-wait-repeat-on-sighup

# Start server
start() {
    $CMD &
    SERVERPID=$!
    SERVERACTIVE=true
}

cont() {
    SERVERACTIVE=false
    kill -SIGCONT $SERVERPID
}

stop() {
    SERVERACTIVE=false
    kill -SIGSTOP $SERVERPID
}

terminate() {
    SERVERACTIVE=false
    kill -SIGKILL $SERVERPID
}

force-terminate() {
    SERVERACTIVE=false
    kill -SIGKILL $SERVERPID
}

# Catch signal to sent it to the server
trap cont            SIGCONT
trap stop            SIGTSTP SIGTTIN SIGTTOU
trap terminate       SIGHUP SIGINT SIGTERM
trap force-terminate EXIT

# Start server
start

# Initialize database
#...
if [ -e /tmp/geo.sql ]
then
  sleep 1m
  psql -d postgres < /tmp/geo.sql
  rm /tmp/geo.sql
fi

# Main loop
while $SERVERACTIVE; do
    wait $SERVERPID
done
