#!/bin/sh
#
# Alban Kraus
# 31 mars 2016
#
# This script watches the modifications of Geoserver mount point, and
# triggers catalog reload on all servers


reload () {
#    for ip in $ipaddr
#    do
#	wget -qO- --ask-password --user=admin --method=PUT http://192.168.1.255:8080/geoserver/rest/reload >/dev/null
#	if [ $? -ne 0 ]
#	then
#	    logger --priority daemon.warning "Failed to reload geoservers."
#	fi
    #    done
    logger --priority daemon.info "Update geoservers."
}

servers="192.168.1.31 192.168.1.37 192.168.1.38 192.168.1.29"

password=geoserver

while true
do
    for ip in $servers
    do
	echo "Reloading server $ip"
	wget -qO- --password=$password --user=admin --method=PUT http://${ip}:8080/geoserver/rest/reload >/dev/null
	sleep 20s
    done
done
