#!/bin/sh
#
# Alban Kraus
# 31 mars 2016
#
# This script watches the modifications of Geoserver mount point, and
# triggers catalog reload on all servers

gsfolder=/var/geoserver

# Get IP addresses

# Watch folder

# Enable trigger

# Reload catalog
for $ip in $ipaddr
do
    wget -qO- --ask-password --user=admin --method=PUT http://192.168.1.255:8080/geoserver/rest/reload
    if [ $? -ne 0 ]
    then
	logger --priority daemon.warning "Failed to reload geoservers."
    fi
done
