version: '2'

services:
  pgpool1:
    image: aaiache/arm-pgpool
    networks:
      - default
    ports:
      - "15432:5432"
    environment:
      - "constraint:node==node1"
  
  postgis1:
    image: alkra/arm-postgis:5.6
    networks:
      - default
    environment:
      - "constraint:node==node1"
  postgis2:
    image: alkra/arm-postgis:5.6
    networks:
      - default
    environment:
      - "constraint:node==node1"

  geoserver1:
    image: vsasyan/geoserver
    ports:
      - "8080:8080"
    volumes:
      - /mnt/geoserver:/var/lib/tomcat7/webapps/geoserver
    networks:
      - default
    environment:
      - "constraint:node==node2"
  geoserver2:
    image: vsasyan/geoserver
    ports:
      - "8080:8080"
    volumes:
      - /mnt/geoserver:/var/lib/tomcat7/webapps/geoserver
    networks:
      - default
    environment:
      - "constraint:node==node3"
  geoserver3:
    image: vsasyan/geoserver
    ports:
      - "8080:8080"
    volumes:
      - /mnt/geoserver:/var/lib/tomcat7/webapps/geoserver
    networks:
      - default
    environment:
      - "constraint:node==node4"



networks:
  default:
    external:
      name: ava
