version: '2'

services:
  haproxy1:
    image: vsasyan/arm-haproxy
    ports:
      -  "80:80"
      -  "8888:8080"
    networks:
      - default
    environment:
      - "constraint:node==node1"
  haproxy2:
    image: vsasyan/arm-haproxy
    ports:
      -  "80:80"
      -  "8888:8080"
    environment:
      - "constraint:node==node2"
    networks:
      - default
  haproxy3:
    image: vsasyan/arm-haproxy
    ports:
      -  "80:80"
      -  "8888:8080"
    environment:
      - "constraint:node==node3"
    networks:
      - default
  haproxy4:
    image: vsasyan/arm-haproxy
    ports:
      -  "80:80"
      -  "8888:8080"
    environment:
      - "constraint:node==node4"
    networks:
      - default

  pgpool1:
    image: aaiache/arm-pgpool
    networks:
      - default
    ports:
      - "15432:5432"
  pgpool2:
    image: aaiache/arm-pgpool
    networks:
      - default
    ports:
      - "15432:5432"

  postgis1:
    image: alkra/arm-postgis:5.5
    networks:
      - default
  postgis2:
    image: alkra/arm-postgis:5.5
    networks:
      - default

  geoserver1:
    image: vsasyan/geoserver:1.0.0
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - /mnt/geoserver:/var/lib/tomcat7/webapps/geoserver
    networks:
      - default
  geoserver2:
    image: vsasyan/geoserver:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - /mnt/geoserver:/var/lib/tomcat7/webapps/geoserver
    networks:
      - default
  geoserver3:
    image: vsasyan/geoserver:1.0.0
    ports:
      - "8080:8080"
    volumes:
      - /mnt/geoserver:/var/lib/tomcat7/webapps/geoserver
    networks:
      - default

networks:
  default:
    external:
      name: ava
